export enum UnleashErrorCode {
  STRATEGY_INVALID_PARAMETER = 'STRATEGY_INVALID_PARAMETER',
  STRATEGY_MISSING_PARAMETER = 'STRATEGY_MISSING_PARAMETER',
  UNEXPECTED_UNLEASH_ERROR = 'UNEXPECTED_UNLEASH_ERROR',
  NOT_FOUND_UNLEASH_ERROR = 'NOT_FOUND_UNLEASH_ERROR',
}
