export const UNLEASH_CLIENT_MODULE_OPTIONS = 'FIREBASE_ADMIN_MODULE_OPTIONS';
export const UNLEASH_CLIENT_INJECT = 'FIREBASE_ADMIN_INJECT';
export const UNLEASH_CLIENT_CONFIG = 'FIREBASE_ADMIN_CONFIG';
